class OrgfileWriter
  def initialize(f)
    @f = f
  end

  def write_header
    @f.write("#  in Emacs, add this file to org-agenda-files\n")
    @f.write("#  DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN\n")
    @f.write("\n\n\n\n")
    @f.write("* TPL\n:PROPERTIES:\n:CATEGORY: TPL\n:END:\n\n\n")
  end

  def create_entrys(xh, actiontype)
    xh.hash.each do |key, value|
      items = value
      datestring = key
      entry_header = '*** TODO '
      entry = "#{entry_header} #{actiontype}\nDEADLINE: #{datestring}\n"
      entry = assemble_book_list(items, entry)
      @f.write(entry)
    end
  end

  def assemble_book_list(items, entry)
    items.each do |l|
      entry += append_unordered_list_element(l)
    end
    entry
  end

  def append_checkbox_item(l)
    " - [ ] #{l}\n"
  end

  def append_unordered_list_element(l)
    " - #{l}\n"
  end
end
